let num1 = parseFloat(prompt('Digite um número: '))
let num2 = parseFloat(prompt('Digite outro número: '))
let soma = num1 + num2
let sub = num1 - num2
let multi = num1*num2
let divisao = num1/num2
let media = (num1+ num2)/2
document.getElementById('resultado').innerHTML = 'Os números digitados foram<br>' + num1 + ' e<br>' + num2 + '.'
document.getElementById('resultado2').innerHTML = 'A soma dos números<br>' + num1 + ' e<br>' + num2 + 'é<br>' + soma + '.'
document.getElementById('resultado3').innerHTML = 'A subtração dos números<br>' + num1 + ' e<br>' + num2 + 'é<br>' + sub + '.'
document.getElementById('resultado4').innerHTML = 'A multiplicação dos números<br>' + num1 + ' e<br>' + num2 + 'é<br>' + multi + '.'
document.getElementById('resultado5').innerHTML = 'A divisão dos números<br>' + num1 + ' e<br>' + num2 + 'é<br>' + divisao + '.'
document.getElementById('resultado6').innerHTML = 'A média dos números<br>' + num1 + 'e<br>' + num2 + 'é<br>' + media + '.'
